### ISSUE TITLE
Linter sporadically failing to run

### ISSUE THREAD

**Issue by gggritso** [aki77/vscode-haml-lint#1]
Really glad to see this extension on the Marketplace, it’s hugely helpful! Thanks for taking this on. I’m running into a sporadic issue where the linter fails to run on files I open. When I open the developer console, this is what I get:

![screen shot 2018-07-23 at 11 35 16 am](https://user-images.githubusercontent.com/989898/43086984-b29924c8-8e6c-11e8-9680-a6a40e60300b.png)

Happy to provide more environment information if you need it!

**Comment by aki77** [comment]
Thanks for the report.
Can you prepare a HAML file to reproduce?

**Comment by gggritso** [comment]
Sort of? I’m about 90% sure the error is caused by `haml-lint` throwing an error at line 0, so VS Code freaks out when VS Code’s `Range` gets a line number of negative 1.

```
/Users/<omitted>file.haml:0 [W] ViewLength: View template is too long [129/100]
```

**Comment by aki77** [comment]
Please try version 0.0.3.

**Comment by gggritso** [comment]
Looks good to me, thank you!
