### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by Juneezee** [aki77/vscode-haml-lint#3]
![image](https://user-images.githubusercontent.com/20135478/79435310-5fc22580-7fc7-11ea-9f50-14df09c564f0.png)

**Comment by aki77** [comment]
Please tell me what haml file and configuration file to reproduce.

**Comment by Juneezee** [comment]
This is the HAML file
```
%footer.footer
  .container
    .columns.is-mobile.is-multiline
      .column.text-center
        = link_to root_path do
          = image_tag 'logo/logo_vertical.svg', width: 100
        %p
          %a.icon.is-large
            - # the extension is supposed to raise SpaceInsideHashAttribute on the line below
            %span.iconify.linkedin{'data-icon': 'brandico:linkedin'} 
        %p Copyright &copy; 2020
```

EDIT: This is my `settings.json` for this extension
```json
{
    "hamlLint.executablePath": "/home/jun/.rvm/gems/ruby-2.6.2/bin/haml-lint",
}
```

**Comment by ryan2johnson9** [comment]
same here

"hamlLint.executablePath": "haml-lint"
"hamlLint.useBundler": false

but I am using in a remote container via vs code remote plugin, if I get a bash in that container I cannot find any haml-lint executable
