### ISSUE TITLE
Lint on save

### ISSUE THREAD

**Issue by danielsvane** [aki77/vscode-haml-lint#6]
I'm not sure this is an issue, but a google result doesn't return anything. Is there an option for fixing the linting errors when saving the file, like there is for rubocop?

**Comment by aki77** [comment]
Thanks for the comment.
It's difficult unless the haml-lint gem implements the autocorrect feature.
See the following for details.
https://github.com/sds/haml-lint/issues/217

**Comment by ndbroadbent** [comment]
Hi @aki77, it looks like autocorrect support was added: https://github.com/sds/haml-lint/pull/346

We can now run `haml_lint -A / -a` to autocorrect files. It would be great to have this support in the VS Code extension if possible. Thanks!
