### ISSUE TITLE
How often does the linter run?

### ISSUE THREAD

**Issue by ingeniousgenius** [aki77/vscode-haml-lint#7]
When I make changes to fix an error, even after saving the error still appears. I have to close/re-open the file in order for the error to go away, or wait an amount of time (which I haven't figured out yet)

Is there a way to customise this

**Comment by aki77** [comment]
Linter is executed when the file is saved.
The `haml-lint` command takes some time to run, so you may need to wait a few seconds for it to be reflected.

https://github.com/aki77/vscode-haml-lint/blob/master/src/extension.ts#L15-L17
